### ISSUE TITLE
Newest lidar version breaks install (pygdal)

### ISSUE THREAD

**Issue by geotom** [opengeos/lidar#21]
* lidar version: 0.6.2
* Python version: 3.8
* Operating System: osgeo/gdal:ubuntu-small-latest (Docker)

### Description

When rebuilding my Python image based on the osgeo/gdal image, I face an installation issue since lidar version 0.6.2. The Pip install fails with the following error:

```
#6 189.9 Collecting pygdal==1.10.0.0
#6 189.9   Downloading pygdal-1.10.0.0.tar.gz (313 kB)
#6 190.5     ERROR: Command errored out with exit status 1:
#6 190.5      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oibtxg54/pygdal/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oibtxg54/pygdal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-oibtxg54/pygdal/pip-egg-info
#6 190.5          cwd: /tmp/pip-install-oibtxg54/pygdal/
#6 190.5     Complete output (42 lines):
#6 190.5     running egg_info
#6 190.5     creating /tmp/pip-install-oibtxg54/pygdal/pip-egg-info/pygdal.egg-info
#6 190.5     writing /tmp/pip-install-oibtxg54/pygdal/pip-egg-info/pygdal.egg-info/PKG-INFO
#6 190.5     writing dependency_links to /tmp/pip-install-oibtxg54/pygdal/pip-egg-info/pygdal.egg-info/dependency_links.txt
#6 190.5     writing requirements to /tmp/pip-install-oibtxg54/pygdal/pip-egg-info/pygdal.egg-info/requires.txt
#6 190.5     writing top-level names to /tmp/pip-install-oibtxg54/pygdal/pip-egg-info/pygdal.egg-info/top_level.txt
#6 190.5     writing manifest file '/tmp/pip-install-oibtxg54/pygdal/pip-egg-info/pygdal.egg-info/SOURCES.txt'
#6 190.5     Traceback (most recent call last):
#6 190.5       File "<string>", line 1, in <module>
#6 190.5       File "/tmp/pip-install-oibtxg54/pygdal/setup.py", line 142, in <module>
#6 190.5         setup(
#6 190.5       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
#6 190.5         return distutils.core.setup(**attrs)
#6 190.5       File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
#6 190.5         dist.run_commands()
#6 190.5       File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
#6 190.5         self.run_command(cmd)
#6 190.5       File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
#6 190.5         cmd_obj.run()
#6 190.5       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 297, in run
#6 190.5         self.find_sources()
#6 190.5       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 304, in find_sources
#6 190.5         mm.run()
#6 190.5       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 535, in run
#6 190.5         self.add_defaults()
#6 190.5       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 571, in add_defaults
#6 190.5         sdist.add_defaults(self)
#6 190.5       File "/usr/lib/python3.8/distutils/command/sdist.py", line 228, in add_defaults
#6 190.5         self._add_defaults_ext()
#6 190.5       File "/usr/lib/python3.8/distutils/command/sdist.py", line 311, in _add_defaults_ext
#6 190.5         build_ext = self.get_finalized_command('build_ext')
#6 190.5       File "/usr/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
#6 190.5         cmd_obj.ensure_finalized()
#6 190.5       File "/usr/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
#6 190.5         self.finalize_options()
#6 190.5       File "/tmp/pip-install-oibtxg54/pygdal/setup.py", line 61, in finalize_options
#6 190.5         self.library_dirs.append(os.path.join(self.gdaldir, 'lib'))
#6 190.5       File "/usr/lib/python3.8/posixpath.py", line 90, in join
#6 190.5         genericpath._check_arg_types('join', a, *p)
#6 190.5       File "/usr/lib/python3.8/genericpath.py", line 155, in _check_arg_types
#6 190.5         raise TypeError("Can't mix strings and bytes in path components") from None
#6 190.5     TypeError: Can't mix strings and bytes in path components
#6 190.5     ----------------------------------------
#6 190.6 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#6 ERROR: executor failed running [/bin/sh -c apt-get update     && apt install -y --no-install-recommends         python3-tk         python3-dev         python3-pip         python3-gdal         python3-distutils         g++     && pip install --no-cache-dir pipenv_to_requirements     && pipenv run pipenv_to_requirements     && pip install --no-cache-dir -r requirements.txt     && pip uninstall -y pipenv_to_requirements     && apt-get remove -y         python3-pip         python3-dev         g++     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*     && echo "from whitebox.whitebox_tools import WhiteboxTools" > wb.py     && echo "wbt = WhiteboxTools()" >> wb.py     && python3 wb.py     && chmod -R 0777 `find / -type d -name "whitebox"`     && rm wb.py     && rm Pipfile     && rm requirements.txt]: exit code: 1
------
 > [3/3] RUN apt-get update     && apt install -y --no-install-recommends         python3-tk         python3-dev         python3-pip         python3-gdal         python3-distutils         g++     && pip install --no-cache-dir pipenv_to_requirements     && pipenv run pipenv_to_requirements     && pip install --no-cache-dir -r requirements.txt     && pip uninstall -y pipenv_to_requirements     && apt-get remove -y         python3-pip         python3-dev         g++     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*     && echo "from whitebox.whitebox_tools import WhiteboxTools" > wb.py     && echo "wbt = WhiteboxTools()" >> wb.py     && python3 wb.py     && chmod -R 0777 `find / -type d -name "whitebox"`     && rm wb.py     && rm Pipfile     && rm requirements.txt:
------
executor failed running [/bin/sh -c apt-get update     && apt install -y --no-install-recommends         python3-tk         python3-dev         python3-pip         python3-gdal         python3-distutils         g++     && pip install --no-cache-dir pipenv_to_requirements     && pipenv run pipenv_to_requirements     && pip install --no-cache-dir -r requirements.txt     && pip uninstall -y pipenv_to_requirements     && apt-get remove -y         python3-pip         python3-dev         g++     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*     && echo "from whitebox.whitebox_tools import WhiteboxTools" > wb.py     && echo "wbt = WhiteboxTools()" >> wb.py     && python3 wb.py     && chmod -R 0777 `find / -type d -name "whitebox"`     && rm wb.py     && rm Pipfile     && rm requirements.txt]: exit code: 1
Service 'python-env' failed to build : Build failed

Process finished with exit code 1
```

### What I Did

Based on the docker image `osgeo/gdal:ubuntu-small-latest` I install 
- python3-tk
- python3-dev
- python3-gdal
- python3-pip

And then install lidar among my other requirements 
- rasterio
- fiona
- whitebox
- numpy

all listed in a requirements.txt file with a
 
`pip install pip install --no-cache-dir -r requirements.txt`

Pip install fails with the message above

**Comment by giswqs** [comment]
Thank you for reporting. I am not a docker user, so I am not sure exactly when went wrong. Here are some potential solutions:

- lidar v0.6.2 only made some changes to update the gdal version. There are no functional changes to the package. You might try installing an earlier version (e.g., v0.6.1) if it worked for you before. 
- The error message shows that docker is trying to install `pygdal==1.10.0.0`, which is way to old. You might want to find out the gdal version of your docker and install the corresponding pygdal version (https://pypi.org/project/GDAL/#history). Once pygdal is installed successfully, then you should be able to install lidar. 
-  You can try Google Colab: https://colab.research.google.com/github/giswqs/lidar/blob/master/examples/lidar_colab.ipynb

**Comment by geotom** [comment]
Hi. Thanks for your fast response. I just checked the GDAL version in the osgeo image and it says:

`GDAL 3.4.0dev-bcadaf0a530715db604aaddcd66362c25b71e58c, released 2021/10/07`

Such a version string seems to not be supported in your GDAL version detection when I look at the code in
https://github.com/giswqs/lidar/blob/66498a36c4eb184d00bc4cce3ee41de86f53a4cb/setup.py#L34

For me switching back to 0.6.1 fixed it but I having a better version lookup might also make 0.6.2 working
