### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by hafez-ahmad** [opengeos/lidar#31]
* lidar version:
* Python version:3.6
* Operating System: windows 10

### Description
Thank you so much for creating this wonderful tool. I am testing with ArcGIS 2.5 with your dataset. But I am getting errors. Is it related python environment or version? Would you check it, please?

### What I Did
I am testing with your provided dataset.
```
ERROR 032659 updateParameters Syntax Error: Traceback (most recent call last):
  File "C:\Users\hahmad\Downloads\lidar-master\lidar\toolbox\ArcGIS Pro Hydrology Analyst.tbx#ExtrackSink.UpdateParameters.py", line 1, in <module>
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\__init__.py", line 21, in <module>
    import numpy
  File "C:\Users\hahmad\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone1\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\Users\hahmad\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone1\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by giswqs** [comment]
Your ArcGIS Pro version seems outdated. The latest version is 3.0

**Comment by hafez-ahmad** [comment]
Thank you so much for your response. Is it only workable with ArcGIS Pro 3.0?
