### ISSUE TITLE
Support newer versions of tcl

### ISSUE THREAD

**Issue by DManowitz** [opengeos/lidar#38]
* lidar version: 0.7.1
* Python version: 3.7
* Operating System: Windows 10

### Description

When trying to import lidar, I get an error about needing an older version of tcl than required by the Python interpreter.

### What I Did

```
import lidar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\lidar\__init__.py", line 18, in <module>
    from .gui import gui
  File "C:\...\lib\site-packages\lidar\gui.py", line 9, in <module>
    import PySimpleGUI as sg
  File "C:\...\lib\site-packages\PySimpleGUI\__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "C:\...\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 150, in <module>
    tclversion_detailed = tkinter.Tcl().eval('info patchlevel')
  File "C:\...\lib\tkinter\__init__.py", line 2119, in Tcl
    return Tk(screenName, baseName, className, useTk)
  File "C:\...\lib\tkinter\__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:\...\tcl\tcl8.6}

C:/.../tcl/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.12, need exactly 8.6.9
version conflict for package "Tcl": have 8.6.12, need exactly 8.6.9
    while executing
"package require -exact Tcl 8.6.9"
    (file "C:/.../tcl/tcl8.6/init.tcl" line 19)
    invoked from within
"source C:/.../tcl/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"


This probably means that Tcl wasn't installed properly.
```

**Comment by DManowitz** [comment]
Never mind.  Looks like this is actually an issue with pysimplegui.
